### ISSUE TITLE
Mouse down inside - mouseup outside

### ISSUE THREAD

**Issue by Y-Taras** [arkon/ng-click-outside#49]
I used https://echeung.me/ng-click-outside/ playground for experiments.
In latest stable Chrome 73 - when user presses mouse down  inside block and releases button outside ( mouse up) it triggers click outside.
In Firefox latest stable : no click outside is triggered in that case
Expected behaviour: same behaviour in browsers

**Comment by arkon** [comment]
That's an inherent difference between the browsers (i.e. how they handle click event targets), which I'm not sure if I should really be trying to normalize only in the context of this directive.

**Comment by yannicke** [comment]
I'm able to resolve this issue with the clickOutsideEvents property (tested on Chrome only): ```[clickOutsideEvents]="'mousedown'"``` 
the click outside is then triggered on mousedown only.

**Comment by MTandi** [comment]
Senpai, I really don't like this behavior either. 
Did you consider adding a parameter that would limit the distance the cursor can travel between `mousedown` and `mouseup` to trigger the event?
I don't think that coordinate calculation has browser compatibility issues.

It's really annoying when you select some text within the pop-up and it closes just because you overshoot and released the button outside the pop-up.
